DROP TABLE IF EXISTS Component_Properties;

DROP TABLE IF EXISTS Components;

DROP TABLE IF EXISTS Messages;

DROP TABLE IF EXISTS Admins;

DROP TABLE IF EXISTS Cart_Items;

DROP TABLE IF EXISTS Shopping_Session;

DROP TABLE IF EXISTS User_Tokens;

DROP TABLE IF EXISTS User_Addresses;

DROP TABLE IF EXISTS Order_Items;

DROP TABLE IF EXISTS Orders;

DROP TABLE IF EXISTS Payment_Details;

DROP TABLE IF EXISTS Images;

DROP TABLE IF EXISTS Sizes_Available;

DROP TABLE IF EXISTS Products;

DROP TABLE IF EXISTS Admin_Permissions;

DROP TABLE IF EXISTS Admin_Type;

DROP TABLE IF EXISTS Permission_Types;

DROP TABLE IF EXISTS User;

DROP TABLE IF EXISTS Discount;

DROP TABLE IF EXISTS Collections;

DROP TABLE IF EXISTS Category;