DROP VIEW IF EXISTS Product_Size_Chart_Components;

DROP VIEW IF EXISTS Product_Variation_Options;

DROP VIEW IF EXISTS Product_Type_And_Parent;

DROP VIEW IF EXISTS Admin_Type_And_Permission;

DROP TABLE IF EXISTS Early_Access;

DROP TABLE IF EXISTS Available_Currencies;

DROP TABLE IF EXISTS Contact_Form_Emails;

DROP TABLE IF EXISTS Email_List;

DROP TABLE IF EXISTS User_OTP;

DROP TABLE IF EXISTS Messages;

DROP TABLE IF EXISTS Admins;

DROP TABLE IF EXISTS Cart_Items;

DROP TABLE IF EXISTS Cart_Discounts;

DROP TABLE IF EXISTS Shopping_Session;

DROP TABLE IF EXISTS User_Tokens;

DROP TABLE IF EXISTS User_Cards;

DROP TABLE IF EXISTS Order_Discounts;

DROP TABLE IF EXISTS Order_Items;

DROP TABLE IF EXISTS Order_Invoice_Items;

DROP TABLE IF EXISTS Orders;

DROP TABLE IF EXISTS Order_Status;

DROP TABLE IF EXISTS User_Addresses;

DROP TABLE IF EXISTS Addresses;

DROP TABLE IF EXISTS Payment_Details;

DROP TABLE IF EXISTS Admin_Permissions;

DROP TABLE IF EXISTS Admin_Type;

DROP TABLE IF EXISTS Permission_Types;

DROP TABLE IF EXISTS Discount;

DROP TABLE IF EXISTS Members;

DROP TABLE IF EXISTS Member_Types;

DROP TABLE IF EXISTS User;

DROP TABLE IF EXISTS Component_Properties;

DROP TABLE IF EXISTS Components;

DROP TABLE IF EXISTS Images;

DROP TABLE IF EXISTS Size_Chart_Values;

DROP TABLE IF EXISTS Product_Configuration;

DROP TABLE IF EXISTS Product_Item;

DROP TABLE IF EXISTS Products;

DROP TABLE IF EXISTS Size_Chart_Components;

DROP TABLE IF EXISTS Variation_Option;

DROP TABLE IF EXISTS Product_Variations;

DROP TABLE IF EXISTS Product_Type_Parents;

DROP TABLE IF EXISTS Product_Type;

DROP TABLE IF EXISTS Collections;

DROP TABLE IF EXISTS Category;

DROP TABLE IF EXISTS Errors;